//| Copyright - The University of Edinburgh 2015                            |
//|                                                                         |
//| Licensed under the Apache License, Version 2.0 (the "License");         |
//| you may not use this file except in compliance with the License.        |
//| You may obtain a copy of the License at                                 |
//|                                                                         |
//|    http://www.apache.org/licenses/LICENSE-2.0                           |
//|                                                                         |
//| Unless required by applicable law or agreed to in writing, software     |
//| distributed under the License is distributed on an "AS IS" BASIS,       |
//| WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.|
//| See the License for the specific language governing permissions and     |
//| limitations under the License.                                          |
package uk.ac.ed.epcc.webapp.session;

/** Default Web-name {@link AppUserNameFinder}.
 * 
 * This is intended to hold the identity generated by an external (container level) authentication mechanism.
 * @author spb
 *
 */

public class WebNameFinder<AU extends AppUser> extends RemoteFieldNameFinder<AU,WebNameFinder> {

	public static final String WEB_NAME = "WebName";

	/**
	 * @param factory
	 */
	public WebNameFinder(AppUserFactory factory) {
		super(factory, WEB_NAME);
	}

	
	

	

}