// Copyright - The University of Edinburgh 2014
package uk.ac.ed.epcc.webapp.charts;

import uk.ac.ed.epcc.webapp.AppContext;
import uk.ac.ed.epcc.webapp.charts.jfreechart.JFreeScatterPeriodChartData;
import uk.ac.ed.epcc.webapp.time.SplitTimePeriod;

/** A {@link ScatterPeriodChart} is a scatter plot where each point 
 * is generated by a different time period.
 * @author spb
 *
 */
@uk.ac.ed.epcc.webapp.Version("$Id: ScatterPeriodChart.java,v 1.4 2014/09/15 14:30:12 spb Exp $")
public class ScatterPeriodChart<P extends ScatterPeriodPlot> extends Chart<P> {

	/**
	 * @param conn
	 */
	protected ScatterPeriodChart(AppContext conn) {
		super(conn);
	}

	public ScatterPeriodChartData<P> getChartData(){
		return (ScatterPeriodChartData<P>) super.getChartData();
	}
	
	public static ScatterPeriodChart getInstance(AppContext conn, SplitTimePeriod period, int nsplit){
		ScatterPeriodChart chart = new ScatterPeriodChart(conn);
		Class<? extends ScatterPeriodChartData> clazz = conn.getPropertyClass(ScatterPeriodChartData.class, JFreeScatterPeriodChartData.class, "ScatterPeriodChartData");
		
		try {
			ScatterPeriodChartData chart_data = conn.makeObject(clazz);
			chart_data.setPeriod(period, nsplit);
			chart.setChartData(chart_data);
		} catch (Exception e) {
			conn.error(e,"Error making TimeChartData");
			return null;
		}
		
		return chart;
	}
}
