// Copyright - The University of Edinburgh 2011
/*******************************************************************************
 * Copyright (c) - The University of Edinburgh 2010
 *******************************************************************************/
package uk.ac.ed.epcc.webapp.jdbc.expr;




/** An object that can produce a SQL expression
 * suitable for use in a select statement. Though functionally the same as SQLValue
 * when objects implement this interface the SQL fragment and the returned object should be 
 * equivalent allowing SQLExpressions to be combined together in java or in SQL without changing the 
 * meaning of the expression. 
 * 
 * 
 * SQLExpressions have to only generate a single result field so the add method must return 1;
 * 
 * @author spb
 * @param <T> Java Type generated by expression
 
 *
 */
public interface SQLExpression<T> extends SQLValue<T>{
	public int hashCode();
	public boolean equals(Object o);
}