//| Copyright - The University of Edinburgh 2011                            |
//|                                                                         |
//| Licensed under the Apache License, Version 2.0 (the "License");         |
//| you may not use this file except in compliance with the License.        |
//| You may obtain a copy of the License at                                 |
//|                                                                         |
//|    http://www.apache.org/licenses/LICENSE-2.0                           |
//|                                                                         |
//| Unless required by applicable law or agreed to in writing, software     |
//| distributed under the License is distributed on an "AS IS" BASIS,       |
//| WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.|
//| See the License for the specific language governing permissions and     |
//| limitations under the License.                                          |
/*******************************************************************************
 * Copyright (c) - The University of Edinburgh 2010
 *******************************************************************************/
package uk.ac.ed.epcc.webapp.jdbc.expr;




/** An object that can produce a SQL expression
 * suitable for use in a select statement. Though functionally the same as SQLValue
 * when objects implement this interface the SQL fragment and the returned object should be 
 * equivalent allowing SQLExpressions to be combined together in java or in SQL without changing the 
 * meaning of the expression. 
 * 
 * 
 * SQLExpressions have to only generate a single result field so the add method must return 1;
 * 
 * @author spb
 * @param <T> Java Type generated by expression
 
 *
 */
public interface SQLExpression<T> extends SQLValue<T>{
	public int hashCode();
	public boolean equals(Object o);
}